name: Build and Release Linux Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build binary for Linux
        run: GOOS=linux GOARCH=amd64 go build -o deploy-action_linux ./deploy.go

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: deploy-action_linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
